spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopsy
    username: shopsy
    password: shopsy
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8082
